name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  VERSION: 0.0.1

jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v6
      - name: Prepare environment
        run: |
          bash ./gsdo/prepare/java.sh
          bash ./gsdo/prepare/gradle.sh
          bash ./gsdo/prepare/sonarscanner.sh
      - name: Run a multi-line script
        run: |
          bash ./gsdo/build/build.sh
  deploy:
    runs-on: deploy
    needs: build
    steps:
      - name: Force clean workspace
        run: rm -rf ./* ./.??* || true
      - name: Checkout deployment logic
        uses: actions/checkout@v6
        with:
          clean: true
          sparse-checkout: |
            gsdo/deploy
            !grad*
            !*.kts
          sparse-checkout-cone-mode: false
      - name: Deploy
        run: |
          ls -alh .
          ls -alh ./gsdo
          ls -alh ./gsdo/deploy
          bash ./gsdo/deploy/deploy.sh
